// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwDYmc5WWh4ODxZIMZ5sjhio70hddGZk4',
    appId: '1:1031656325299:web:60e644774b8812a868f0c6',
    messagingSenderId: '1031656325299',
    projectId: 'fluttercontactfirebase-7e746',
    authDomain: 'fluttercontactfirebase-7e746.firebaseapp.com',
    storageBucket: 'fluttercontactfirebase-7e746.firebasestorage.app',
    measurementId: 'G-5PBGJNX2ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpkEOXpmscRaaUGTJsKeMO4z1VsVISfJA',
    appId: '1:1031656325299:android:8a6587ad5ca4a50668f0c6',
    messagingSenderId: '1031656325299',
    projectId: 'fluttercontactfirebase-7e746',
    storageBucket: 'fluttercontactfirebase-7e746.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpBoiumaxl7ideQJ2dgIdQ3KsHLtcBhaE',
    appId: '1:1031656325299:ios:175a1ffb989445d368f0c6',
    messagingSenderId: '1031656325299',
    projectId: 'fluttercontactfirebase-7e746',
    storageBucket: 'fluttercontactfirebase-7e746.firebasestorage.app',
    iosBundleId: 'com.example.flutterContactFirebase',
  );

}