name: Generate Dokumentasi

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install TeX Live and texlive-latex-extra
      - name: Install TeX Live with texlive-latex-extra
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended texlive-lang-all

      # Install additional TeX Live packages from file
      - name: Install Additional TeX Live Packages
        run: |
          while read -r package; do
            sudo tlmgr install "$package"
          done < .github/tex_deps.txt

      # Setup Pandoc
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      # Generate PDF using the script
      - name: Generate PDF
        run: bash ../.github/docs.sh "Rizal Fadlullah" "A11.2019.12070"
        working-directory: praktikum_8

      # Upload the generated PDF as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-result
          path: praktikum_8/PRAKTIKUM_8.pdf
