name: Generate Dokumentasi

on:
  workflow_dispatch:
  push:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          package-file: |
            ./.github/template_deps.txt
            ./.github/basictex_deps.txt

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: 3.5

      - name: Run documentation script
        run: bash ../.github/docs.sh "Rizal Fadlullah" "A11.2019.12070"
        working-directory: praktikum_8

      - name: Upload a file to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          filename: ./praktikum_8/PRAKTIKUM_8.pdf
          credentials: ${{ secrets.CREDENTIALS }}
          folderId: ${{ secrets.FOLDER_ID }}
          overwrite: true 

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-result  # Nama artifact
          path: ./praktikum_8/PRAKTIKUM_8.pdf  # Path file/folder yang akan di-upload
