name: Generate Dokumentasi

on:
  workflow_dispatch:
  push:

jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          [
            praktikum_1,
            praktikum_2,
            praktikum_3,
            praktikum_4,
            praktikum_5,
            praktikum_6,
            praktikum_7,
            praktikum_8,
            praktikum_9,
            praktikum_10,
            praktikum_11,
            praktikum_12,
            praktikum_13,
            praktikum_14,
            uts,
            uas,
          ]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dokumentasi
        id: cache-docs
        uses: actions/cache@v4
        with:
          path: dokumentasi
          key: ${{ runner.os }}-dokumentasi

      - name: Get changed directory
        id: change-dirs
        run: |
          dirs=$(git diff main --name-only | awk -F/ '{print $1}' | sort -u)
          echo "Changed directories: $dirs"
          echo "changed_dirs=$dirs" >> $GITHUB_ENV

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          package-file: |
            ./.github/template_deps.txt
            ./.github/basictex_deps.txt

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: 3.5

      - name: Run documentation script
        run: |
          if echo "${{ env.change-dirs }}" | grep -qw "${{ matrix.directory }}"; then
            echo "Directory ${{ matrix.directory }} has changed. Running documentation script..."
            bash ../.github/docs.sh "${{ vars.NAMA }}" "${{ vars.NIM }}"
          else
            echo "Directory ${{ matrix.directory }} does not exist. Skipping..."
          fi
        working-directory: ${{ matrix.directory }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dokumentasi
          path: dokumentasi

      - name: Upload a file to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          filename: ./dokumentasi/PRAKTIKUM_8.pdf
          credentials: ${{ secrets.CREDENTIALS }}
          folderId: ${{ secrets.FOLDER_ID }}
          overwrite: true
