name: Generate Dokumentasi
on: workflow_dispatch

jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        schemes:
          - scheme-basic scheme-infraonly
          - scheme-basic scheme-minimal
          - scheme-basic scheme-small
          - scheme-infraonly scheme-minimal
          - scheme-infraonly scheme-small
          - scheme-minimal scheme-small
          - scheme-basic scheme-infraonly scheme-minimal
          - scheme-basic scheme-infraonly scheme-small
          - scheme-basic scheme-minimal scheme-small
          - scheme-infraonly scheme-minimal scheme-small
          - scheme-basic scheme-infraonly scheme-minimal scheme-small
        collections:
          - collection-basic
          - collection-latex
          - collection-latexrecomended
          - collection-metapost
          - collection-xetex
          - collection-basic collection-latex
          - collection-basic collection-latexrecomended
          - collection-basic collection-metapost
          - collection-basic collection-xetex
          - collection-latex collection-latexrecomended
          - collection-latex collection-metapost
          - collection-latex collection-xetex
          - collection-latexrecomended collection-metapost
          - collection-latexrecomended collection-xetex
          - collection-metapost collection-xetex
          - collection-basic collection-latex collection-latexrecomended
          - collection-basic collection-latex collection-metapost
          - collection-basic collection-latex collection-xetex
          - collection-basic collection-latexrecomended collection-metapost
          - collection-basic collection-latexrecomended collection-xetex
          - collection-basic collection-metapost collection-xetex
          - collection-latex collection-latexrecomended collection-metapost
          - collection-latex collection-latexrecomended collection-xetex
          - collection-latex collection-metapost collection-xetex
          - collection-latexrecomended collection-metapost collection-xetex
          - collection-basic collection-latex collection-latexrecomended collection-metapost
          - collection-basic collection-latex collection-latexrecomended collection-xetex
          - collection-basic collection-latex collection-metapost collection-xetex
          - collection-basic collection-latexrecomended collection-metapost collection-xetex
          - collection-latex collection-latexrecomended collection-metapost collection-xetex
          - collection-basic collection-latex collection-latexrecomended collection-metapost collection-xetex
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          cache: false
          package-file: ./.github/tex_deps.txt
          packages: ${{ matrix.schemes }} ${{ matrix.collections }}
      - uses: r-lib/actions/setup-pandoc@v2
      - run: ../.github/docs.sh "Rizal Fadlullah" "A11.2019.12070"
        working-directory: praktikum_8
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-result  # Nama artifact
          path: ./praktikum_8/PRAKTIKUM_8.pdf   # Path file/folder yang akan di-upload
