name: Generate Dokumentasi V2

on:
  workflow_dispatch:
  push:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick texlive-latex-extra xzdec
          sudo tlmgr update --self || echo "Skipping update due to Debian-specific limitations."
          mkdir -p $HOME/texmf
          sudo tlmgr init-usertree

          if [[ -f .github/template_deps.txt ]]; then
            while IFS= read -r package; do
              sudo tlmgr install "$package" || echo "Failed to install $package. Skipping."
            done < .github/template_deps.txt
          else
            echo "Dependency file not found: .github/template_deps.txt"
            exit 1
          fi

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Run Documentation Script
        run: bash ../.github/docs.sh "Rizal Fadlullah" "A11.2019.12070"
        working-directory: praktikum_8

      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          filename: ./praktikum_8/PRAKTIKUM_8.pdf
          credentials: ${{ secrets.CREDENTIALS }}
          folderId: ${{ secrets.FOLDER_ID }}
          overwrite: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-result
          path: ./praktikum_8/PRAKTIKUM_8.pdf
          