# .github/workflows/main.yml
name: Main
on: workflow_dispatch

jobs:
  my_job:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload a file to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          filename: PRAKTIKUM_8.pdf
          credentials: ${{ secrets.CREDENTIALS }}
          folderId: ${{ secrets.FOLDER_ID }}
          overwrite: true          
